>U14387.1_Pseudopedinella_elastica_18S_small-subunit_rRNA_gene
cacctggttgatcctgccagtagtcatacgcttgtctcaaagattaagccatgcatgtct
aagtataaacgactctatactgtgaaactgcgtacggctcattaaaccagttatagttta
tttgatattcccctactactcggatacccgtagtaattctagagctaatacgtgcgtcaa
acgacattt------------gtcgtgtcattattagatagaaaccaatgcggcttcgg-
-ccggtattgtggtgagtcatgataatttagcggatcgcatggtctcgtaccggcgatgg
atcattcaagtttctgccctatcagctttggatggtagggtattggcctaccatggcttt
aacgggtaacggagaattagggttcgattccggagagggagcctgagagacggctaccac
atccaaggaaggcagcag--gcgcgtaaattacccaatcctgacacagggaggtagtgac
aaaaaataacttagtcgggccg-ttttcggtctgactttaggaatgagaacaatttaaat
cccttatcgaggatcaattggagggcaagtctggtgccagcagccgcggtaattccagct
ccaatagcgtatattaatgttgttgcagttaaaaagctcgtagttggatttctgg-attg
agcg-gctg--gccttgcgcgcaagcgttcgtgtc---ggcttcgtttcggtccatcctc
aggg-------ggacttgcgctggcattaacgtgtc-ggtgttgggacgcctgtcgttta
ctgtgaacaaattagagtgttcaaagcaaggtg------tacttgaatacattagcatgg
aat-aataagataggactttggtgg-ttct---------------------tttt-gata
ttttgttggtttgcacgccaaagtaatgattaataggagcagttgggggtattcgtattc
aattgtcagaggtgaaattcttggatttatagaagacgaactactgcgaaagcatttacc
aaggatgttttcattaatcaagaacgaaagttaggggatcgaagaagattagataccttc
gtagtccta-accataaactatgccgactcgggattggcggtcgt------------ttt
tttaccgactccgtcagcaccgtatgagaaatcaaagtctttgggttccggggggagtat
ggtcgcaaggctgaaacttaaagaaattgacggaagggcaccaccaggagtggagcctgc
ggcttaatttgactcaacacggggaaacttaccaggtccagacatagtaaggattgacag
attgagagctctttcttgattctatgggtggtggtgcatggccgttcttagttggtggag
tgatttgtctggttaattccgttaacgaacgagacccccgcctgctaaatagtgctggga
atgc-ttcgcattgccagat---cgcttcttagagggacttcgtgtgactaacacgagga
agttgggggcaataacaggtctgtgatgcccttagatgttctgggccgcacgcgcgctac
actgatgcatgcaacgagttt-------acaaccttggccgggaggcctgggtaatctgt
gaacgtgcatcgtgatagggatagattattgcaattattaatcttgaacgaggaattcct
agtaaacgcaagtcaacagcttgcattgattacgtccctgccctttgtacacaccgcccg
tcgcacctaccgatcgaaggtaatgatgagccctcaggacagtcgattggcgcc-ttcac
gggtacct-tttggttgaaatttgtgcaaatccttacctttagaggaaggtgaagtcgta
acaaggttaccgtaggtgaacctgcagaaggatcaagc
>AB081517.1_Pedinella_sp._squamata_gene_for_small_subunit_ribosomal_RNA_partial_sequence
--------------------tagtcatacgcttgtctcaaagattaagccatgcangtcn
aagtataaacaactctntactgtgaaactgcgtacggctcattaaaccagttatagttta
tttgatattcccctactactcggatacccgtagtaattctagagctaatacgtgcgtcaa
acagcattt------------gctgtgtcattattagatagaaaccaatgcggtctcgg-
-ccggtattgtggtgagtcatgataatttagcggatcgcatggctttacgccggcgatgg
atcattcaagtttctgccctatcagctttggatggtagggtattggcctaccatggcttt
aacgggtaacggagaattagggttcgattccggagagggagcctgagagacggctaccac
atccaaggaaggcagcag--gcgcgtaaattacccaatcctgacacagggaggtagtgac
aaaaaataacttagtcgggccg-ttttcggtctgactttaggaatgagaacaatttaaat
cccttatcgaggatcaattggagggcaagtctggtgccagcagccgcggtaattccagct
ccaatagcgtatattaatgttgttgcagttaaaaagctcgtagttggatttctgg-tcgg
aacg-ctgg--tccggctccgcaaggggtcgtg-c---actggtttctccgtccatcctc
aggg-------ggagctgcactggtattcatttatc-ggtgtggtgacgcctgtcgttta
ctgtgaacaaattagagtgttcaaagcaaggtt------aacttgaatacattagcatgg
aat-aataagataggactttggtgg-ttct---------------------tttt-gata
ttttgttggtttgcacgccaaagtaatgattaataggagcagttgggggtattcgtattc
aattgtcagaggtgaaattcttggatttatagaagacgaactactgcgaaagcatttacc
aaggatgttttcattaatcaagaacgaaagttaggggatcgaagaagattagataccttc
gtagtccta-accataaactatgccgactcgggattggcggtcg-------------ttt
tttaccgactccgtcagcaccgtatgagaaatcaaagtctttgggttccggggggagtat
ggtcgcaaggctgaaacttaaagaaattgacggaagggcaccaccaggagtggagcctgc
ggcttaatttgactcaacacggggaaacttaccaggtccagacatagtaaggattgacag
attgagagctctttcttgattctatgggtggtggtgcatggccgttcttagttggtggag
tgatttgtctggttaattccgttaacgaacgagacccccgcctgctaaatagcgcgcggt
atgc-tt-gcatatcgtgct---cgcttcttagagggactttgtgtgactaacacaagga
agttgggggcaataacaggtctgtgatgcccttagatgttctgggccgcacgcgcgctac
actgatgcatgcaacgagtct-------agaaccttggccgggaggcctgggtaatctgt
gaacgtgcatcgtgatagggatagattattgcaattattaatcttgaacgaggaattcct
agtaaacgcaagtcaacagcttgcattgattacgtccctgccctttgtacacaccgcccg
tcgcacctaccgatcgaaggtaatgatgagccctcaggacagttgtttgggtc--ctcac
ggac-ctt-tacgactggaatttgtgcaaatccttgcctttagaggaaggtgaagtcgta
acaaggttaccgtaggtg--------------------
>HQ710561.1_Pseudopedinella_sp_HSY-2011
----------------------------------------------------gcatgtct
aagtataaacaactctatactgtgaaactgcgtacggctcattaaaccagttatagttta
tttgatattcccctactactcggatacccgtagtaattctagagctaatacgtgcgtcaa
acagcattt------------gctgtgtcattattagatagaaaccaatgcggtctcgg-
-ccggtattgtggtgagtcatgataatttagcggatcgcatggctttacgccggcgatgg
atcattcaagtttctgccctatcagctttggatggtagggtattggcctaccatggcttt
aacgggtaacggagaattagggttcgattccggagagggagcctgagagacggctaccac
atccaaggaaggcagcag--gcgcgtaaattacccaatcctgacacagggaggtagtgac
aaaaaataacttagtcgggccg-ttttcggtctgactttaggaatgagaacaatttaaat
cccttatcgaggatcaattggagggcaagtctggtgccagcagccgcggtaattccagct
ccaatagcgtatattaatgttgttgcagttaaaaagctcgtagttggatttctgg-tcgg
aacg-ctgg--tccggctccgcaaggggtcgtg-c---actggtttctccgtccatcctc
aggg-------gtagctgcactggtattcatttatc-ggtgtggtgacgcctgtcgttta
ctgtgaacaaattagagtgttcaaagcaaggtt------tacttgaatacattagcatgg
aat-aataagataggactttggtgg-ttct---------------------tttt-gata
ttttgttggtttgcacgccaaagtaatgattaataggagcagttgggggtattcgtattc
aattgtcagaggtgaaattcttggatttatagaagacgaactactgcgaaagcatttacc
aaggatgttttcattaatcaagaacgaaagttaggggatcgaagaagattagataccttc
gtagtccta-accataaactatgccgactcgggattggcggtcg-------------ttt
tttaccgactccgtcagcaccgtatgagaaatcaaagtctttgggttccggggggagtat
ggtcgcaaggctgaaacttaaagaaattgacggaagggcaccaccaggagtggagcctgc
ggcttaatttgactcaacacggggaaacttaccaggtccagacatagtaaggattgacag
attgagagctctttcttgattctatgggtggtggtgcatggccgttcttagttggtggag
tgatttgtctggttaattccgttaacgaacgagacccccgcctgctaaatagcgcgcggt
atgc-tt-gcatatcgtgct---cgcttcttagagggactttgtgtgactaacacaagga
agttgggggcaataacaggtctgtgatgcccttagatgttctgggccgcacgcgcgctac
actgatgcatgcaacgagtct-------agaaccttggccgggaggcctgggtaatctgt
gaacgtgcatcgtgatagggatagattattgcaattattaatcttgaacgaggaattcct
agtaaacgcaagtcaacagcttgcattgattacgtccctgccctttgtacacaccgcccg
tcgcacctaccgatcgaaggtaatgatgagccctcaggacagttgtttgggtc--ctcac
ggac-ctt-tacgactggaatt--------------------------------------
--------------------------------------
>L37204.1_Pteridomonas_danica_ribosomal_RNA_rRNA
aacctggttgatcctgccagtagtcatacgcttgtctcaaagattaagccatgcatgtct
aagtataaacgaatctatactgtgaaactgcgtacggctcattaaaccagttatagttta
tttgatattcccctactacttggatacccgtagtaattctagagctaatacatgcgtcaa
gcgacatat------------gtcgtgtcattattagatagaaaccaatgcgacttcgg-
-tcggaattgtggtgagtcatgataatttagcggatcgcatggccttgtgccggcgatgg
atcattcaagtttctgccctatcagccttggatggtagggtattggcctaccatggcttt
aacgggtaacggagaaktagggttcgattccggagagggagcctgagagacggctaccac
atccaaggaaggcagcag--gcgcgtaaattacccaatcctgactcagggaggtagtgac
aaaaaataacttagtcgagccg-ttttcggtttgactttaggaatgagaacaatttaaat
cccttatcgaggatcaattggagggcaagtctggtgccagcagccgcggtaattccagct
ccaatagcgtatattaatgttgttgcagttaaaaagctcgtagttggatttctgg-tcgg
aacg-cctg--gccggctccgcaaggggtcgttgc--attggctgttttcgtccatcctc
aggg-------gaacttgctctggtattaatttatc-ggtgtaaggacgcctgtcgttta
ctgtgaacaaattagagtgttcaaagcaaggtg------tacttgaatacattagcatgg
aat-aataagataggactttggtgg-ttct---------------------ttttagata
ttttgttggtttgcacgccaaagtaatgattaataggagcagttgggggtattcgtattc
aattgtcagaggtgaaattcttggatttatagaagacgaagtactgcgaaagcatttacc
aaggatgttttcattaatcaagaacgaaagttaggggatcgaagaagattagataccttc
gtagtccta-accataaaccatgccgactcgggattggcggtcgtta----------ctt
tttatcgactccgtcagcaccgtatgagaaatcaaagtctttgggttccggggggagtat
ggtcgcaaggctgaaacttaaagaaattgacggaagggcaccaccaggagtggagcctgc
ggcttaatttgactcaacacggggaaacttaccaggtccagacatagtaaggattgacag
attgagagctctttcttgattctatgggtggtggtgcatggccgttcttagttggtggag
tgatttgtctggttaattccgttaacgaacgagacccccgcctgctaaatagtgccatta
atgc-ttcgcattggtggat---cgcttcttagagggactgtatgagactatcatacgga
agttgggggcaataacaggtctgtgatgcccttagatgtcctgggccgcacgcgcgctac
actgatacgtgcaacaagtat------aagaaccttggccgggaggcctgggtaatcttt
gaacgcgtatcgtgatagggatagattattgcaattattaatcttgaacgaggaattcct
agtaaacgcaagtcatcagcttgcattgattacgtccctgccctttgtacacaccgcccg
tcgcacctaccgatcgaaggtaatgatgagcccgcaggaccgctgatttagcc--ttcac
gggc-ttt-ttcggttgaaatttctgcaaatccttgcctttagaggaaggtgaagtcgta
acaaggttaccgtaggtgaacctgcagaaggatc----
>AB081640.1_Pteridomonas_danica_gene_for_18S_rRNA_partial_sequence
--------------------tagtcatacgcttgtctcaaagattaagccatgcatgtct
aagtataaacgaatctatactgtgaaactgcgtacggctcattaaaccagttatagttta
tttgatattcccctactacttggatacccgtagtaattctagagctaatacatgcgtcaa
gcgacatat------------gtcgtgtcattattagatagaaaccaatgcgacttcgg-
-tcggaattgtggtgagtcatgataatttagcggatcgcatggccttgtgccggcgatgg
atcattcaagtttctgccctatcagctntggatggtagggtattggcctaccatggcttt
aacgggtaacggagaattagggttcgattccggagagggagcctgagagacggctaccac
atccaaggaaggcagcag--gcgcgtaaattacccaatcctgactcagggaggtagtgac
aaaaaataacttagtcgagccg-ttttcggtttgactttaggaatgagaacaatttaaat
cccttatcgaggatcaattggagggcaagtctggtgccagcagccgcggtaattccagct
ccaatagcgtatattaatgttgttgcagttaaaaagctcgtagttggatttctgg-tcgg
gacg-cctg--gccggctccgcaaggggtcgttgc--attggctgntttcgtccatcctc
aggg-------gaacttgctctggtattaatttatc-ggtgtaaggacgcctgtcgttta
ctgtgaacaaattagagtgttcaaagcaaggtg------tacttgaatacattagcatgg
aataaataagataggactttggtgg-ttct---------------------ttttagata
ttttgttggtttgcacgccaaagtaatgattaataggancagttgggggtattcgtattc
aattgtcagaggtgaaattcttggatttat-gaagacgaactactgcgaaagcatttacc
aaggatgttttcattaatcaagaacgaaagttaggggatcgaagaagattagataccttc
gtagtccta-accataaaccatgccgactcgggattggcggtcgtta----------ctt
tttatcgactccgtcagcaccgtatgagaaatcaaagtctttgggttccggggggagtat
ggtcgcaaggctgaaacttaaagaaattgacggaagggcaccaccaggagtggagcctgc
ggcttaatttgactcaacacggggaaacttaccaggtccagacatagtaaggattgacag
attgagagctctttcttgattctatgggtggtggtgcatggccgttcttagttggtggag
tgatttgtctggttaattccgttaacgaacgagacccccgcctgctaaatagtgccatta
atgc-ttcgcantggtggat---cgcttcttagagggactgtatgagactatcatacgga
agtagggggcaataacaggtctgtgatgcccttagatgtcctgggccgcacgcgcgctac
actgatacgtgcaacaagtat-------ngaaccttggccgggaggcctgggttatctnt
gaacgcgtatcgtganagggatagattattgcaattattaatcttgaacgaggaattcct
agtanacgctagtcatcagcttgcatngattacntcccngcccttngtacacaccgcccg
tcgcacctaccgatcgaaggtaatgatgagccgncaggaccgctgatttagcc--ttcac
gggc-tttgttcggttgaaatttctgcaaatccttgcctttagaggaaggtgaagtcgta
acaaggtt------------------------------
>U14384.1_Apedinella_radians_18S_small-subunit_rRNA_gene
cacctggttgatcctgccagtagtcatacgcttgtctcaaagattaagccatgcatgtct
aagtataaacgaatctatactgtgaaactgcgtacggctcattaaaccagttatagttta
tttgatattcccctactacttggatacccgtagtaattctagagctaatacatgcgtcaa
gcgacattt------------gtcgtgtcattattagatagaaaccaatgcgacttcgg-
-tcggaattgtggtgaatcatgataatttagcggatcgcatggccttgcgccggcgatgg
atcattcaagtttctgccctatcagctttggatggtagggtattggcctaccatggcttt
aacgggtaacggagaattagggttcgattccggagagggagcctgagagacggctaccac
atccaaggaaggcagcag--gcgcgtaaattacccaatcctgactcagggaggtagtgac
aaaaaataacttagtcgggccg-ttttcggtctgactttaggaatgagaacaatttaaat
cccttatcgaggatcaattggagggcaagtctggtgccagcagccgcggtaattccagct
ccaatagcgtatattaatgttgttgcagttaaaaagctcgtagttggatttctgg-gttc
ttcg-ctag--ctttggtccgcaagggcttcag-----tgggctgtttgaatccatcctc
aggg-------ggactcatgctggtattcatttatc-ggtgtgggaacgcctgtcgttta
ctgtgaacaaattagagtgttcaaagcaaggtg------tacttgaatacattagcatgg
aat-aataagataggactttggtgg-ttct---------------------ttcgagata
ttttgttggtttgcacgccaaagtaatgattaataggagcagttgggggtattcgtattc
aattgtcagaggtgaaattcttggatttatagaagacgaactactgcgaaagcatttacc
aaggatgttttcattaatcaagaacgaaagttaggggatcgaagaagattagataccttc
gtagtccta-accataaacgatgccgactcgggattggcggtcgat-----------tct
tttatcgtctccgtcagcaccgtatgagaaatcaaagtctttgggttccggggggagtat
ggtcgcaaggctgaaacttaaagaaattgacggaagggcaccaccaggagtggagcctgc
ggcttaatttgactcaacacggggaaacttaccaggtccagacataggaaggattgacag
attgagagctctttcttgattctatgggtggtggtgcatggccgttcttagttggtggag
tgatttgtctggtttattccgttaacgaacgagacccctgcctgctaaatagcgccggga
atgc-ttcgcattgccggat---cgcttcttagagggactgtatgggactaccatacgga
agttgggggcaataacaggtctgtgatgcccttagatgttctgggccgcacgcgcgctac
actgatacgtgcaacaagttt-------agaaccttggccgagaggcctgggtaatcttt
gaacgcgtatcgtgatagggatagattattgcaattattaatcttgaacgaggaattcct
agtaaacgcaagtcatcagcttgcattgattacgtccctgccctttgtacacaccgcccg
tcgcacctaccgatcgaaggtaatgatgagccgtcaggaccgtcggtttggcc--ttaac
gggt-ctt-ttcgactgaaatttctgcaaatccttacctttagaggaaggtgaagtcgta
acaaggttaccgtaggtgaacctgcagaaggatcaagc
>U14388.1_Rhizochromulina_cf_marina_18S_small-subunit_rRNA_gene
cacctggttgatcctgccagtagtcatacgcttgtctcaaagattaagccatgcatgtct
aagtataagcga--ttatactgtgaaactgcgtacggctcattaaaccagttatagttta
tttgatatttccctactactcggatacccgtagtaattctagagctaatacgtgaatgaa
gctccgact------------ggagtgtcattattagatagaaaccaatgcggcgcaag-
-ccggtattgtggtgagtcatgataatttagcggatcgcatggccttgcgccggcgacgg
atcattcaagtttctgccctatcagctttggatggtacggtattggcctaccatggcttt
aacgggtaacggagaattagggttcgattccggagagggagcctgagagacggctaccac
atccaaggaaggcagcag--gcgcgtaaattacccaatcctgacacagggaggtagtgac
aagaaataacttagtcgggcct-ttacgggtctgactttaggaatgagaacaatttaaat
cccttatcgaggatcaattggagggcaagtctggtgccagcagccgcggtaattccagct
ccaatagcgtatattaatgttgttgcagttaaaaagctcgtagttggatttcgaa-tggg
agtg-actg--gtcggctccgcaaggggtcgcaac---cgtgttgtctccggttctcttt
cgggttttctttctggcgtgctggcattcatttgtc-ggtg-cgtcgggcccgtcgttta
ctgtgaacaaattagagtgttccaagcaaggctt-----gacttgaatacattagcatgg
aat-aataagataggactttggtgg-ttccaggtgttcgt-----------gcctggata
ttttgttggtttgcacgccaaagtaatgattaataggagcagttgggggtattcgtattc
aattgtcagaggtgaaattcttggatttctagaagacgaactactgcgaaagcatttacc
aaggatgttttcattaatcaagaacgaaagttaggggatcgaagaagattagataccttc
gtagtccta-accataaacgatgccgactcgggattggcggtcgttggaatgca---aat
tcaaatgactccgtcagcaccgtatgagaaatcaaagtctttgggttccggggggagtat
ggtcgcaaggctgaaacttaaagaaattgacggaagggcaccaccaggagtggagcctgc
ggcttaatttgactcaacacggggaaacttaccaggtccagacatagtaaggattgacag
attgagagctctttcttgattctatgggtggtggtgcatggccgttcttagttggtggag
tgatttgtctggttaattccgttaacgaacgagacccccgcctgctaaatagcgcaggga
atgc-atcgcattgcctggtt--cgcttcttagagggactgtcagtgactaactgacgga
agttgggggcaataacaggtctgtgatgcccttagatgtcctgggccgcacgcgcgctac
actgatgcatgcaacgagttcttt----ttttccttggctggaaggcctgggtaatctgt
gaacgtgcatcgtgatagggatagattattgcaattattaatcttgaacgaggaattcct
agtaaacgcaagtcatcagcttgcattgattacgtccctgccctttgtacacaccgcccg
tcgcacctaccgatcgaaggtaatgatgagcccttaggattgtggcttgggacgggcaac
cgac-cct-cgccgcgagaatttgtgcaaatccctacctttagaggaaggtgaagtcgta
acaaggttaccgtaggtgaacctgcagaaggatcaagc
>L37205.1_Ciliophrys_infusionum_ribosomal_RNA_rRNA
aacctggttgatcctgccagtagtcatacgcttgtctcaaagattaagccatgcatgtct
aagtataagcaa--ttatacagcgaaactgcgtacggctcattaaaccagttattgtttc
tttgatagttccctactactcggataaccgtagtaattctagagctaatacgtgcataag
cctttcttc-----tcggaggagggtgtcattattagatagaaaccaatgcggcgcaac-
---ggtattgtggtgagtcatgataatttcgcggatcgtatggcctcgtgccgacgacgg
atcattcaagtttctgccctatcagctttggatggtacggtattggcctaccatggcttt
aacgggtaacggggaattagggttcgattccggagagggagcctgagagacggctaccac
atccaaggaaggcagcaggcgcgcgtaaattacccaatcctgacacagggaggtagtgac
aagaaataacgtagtcgggcccattttgggtctgactttcggaatgagaacaatttaaat
cccttatcgaggatcaattggagggcaagtctggtgccagcagccgcggtaattccagct
ccaatagcgtatattaatgttgttgcagtt-aaaagctcgtagttggatttcgga-ctgg
agag-gcgg--gccggctccgcaaggggtcgtagcctaatgtcctgctctggttcttttc
ggga---atctctggcgttgctggcatttagttgtc-ggtggcgttggacccgtcgttta
ctgtgaacaaattagagtgtcc-aagcagggtaa--c-ctacttgaatacattagcatgg
aat-aataagataggactttggtgg-ttttgtctcttcactctttgtggagggatgaata
ttttgttggtttgcacgccaaagtaatgattaataggagcagttgggggtattcgtattc
aattgtcagaggtgaaattcttggatttctagaagacgaactactgcgaaagcatttacc
atggacgcgttcattaatcaagaacgaaagttaggggatcgaagaagattagataccttc
gtagtccta-accataaacgatgccgactcgggattggcggtcgttggaattcacaagat
tcaaaagactccgtcagcaccgtatgagaaatcaaagtctttgggttccggggggagtat
ggtcgcaaggctgaaacttaaagaaattgacggaagggcaccaccaggagtggagcctgc
ggcttaatttgactcaacacggggaaacttaccaggtccagacatagtaaggattgacag
attgagagctctttcttgattctatgggtggtggtgcatggccgttcttagttggtggag
tgatttgtctggttaattccgttaacgaacgagacccccgcctgctaaatagcgcactga
atgc-ctagcattgagtgattttcgcttcttagagggactgtcggtgactaatcgacgga
agttgggggcaataacaggtctgtgatgcccttagatgtcctgggccgcacgcgcgctac
actgatgcatgcaacgagtttttcactagtgaccttggccggaaggcttgggaaatctgt
gaacgtgcatcgtgatagggattgatttttgcaattctgaatcataaacgaggaattcct
agtaaacgcaagtcatcagcttgcattgattacgtccctgccc-ttgtacacaccgcccg
tcgcacctaccgatcgaaggtaatgatgagcccttaggattgtcattcttgacacgcaag
tgtt-ggg-agaggcgagaatttgtgcaaatccctacctttagaggaaggtgaagtcgta
acaaggttaccgtaggtgaacctgcagaaggatc----
>AB081641.1_Ciliophrys_infusionum_gene_for_18S_rRNA_partial_sequence
---------------------------------------------------------tct
aagtataagcaa--ttatacagcgaaactgcgtacggctcattaaaccagttatagtttc
tttgatagttccctactactcggataaccgtagtaattctagagctaatacgtgcataag
cctttcttt-----tcggaggagggtgtcattattagatagaaaccaatgcggcgcaag-
-ccggtattgtggtgagtcatgataatttcgcggatcgtatggcctngcgccgacgacgg
atcattcaantttctgccctatcagctttggatggtacggtattgggctaccatggcttt
aacgggtaacggggaattagggttcgattccngagaaggagcctgagagacggctaccac
atccaaggaaggcagcag--gcgcgtaaattacccaatcctgacacagggaggtagtgac
aagaaataacgtagtcgggcgc-ttatgtgtctgactttcggaatgagaacaatttaaat
cccttatcgaggatcaattggagggcaagtctggtgccagcagccgcggtaattccagct
ccaatagcgtatattaatgttgttgcagttaaaaagctcgtagttggatttcgga-ctgg
agag-gcgg--gccggctccgcaaggggtcgtagcctgatgtcctgctctggttcttttc
gggat--ttctcnngcgtttctggcattnatttgtc-ggtggcgttggacccgtcgttta
ctgtgaacaaattagagtgttccaagcagggtaa--c-ctacttgaatacattagcatgg
aat-aataagataggactttggtgg-ttttg-ctgctctcttcacggggggtagtgaata
ttttgttggtttgcacgccaaagtaatgattaataggagcagtngggggtattcgtattc
aattgtcagaggtgaaattcttggatttctagaagacgaattactgcgaaagcatttacc
aaggatgcgttcattaatcaagaacgaaagttaggggatcgaagaagattagataccttc
gtagtctta-accataaacgatgccgactcgggattggcggtcgttggaattcacaagat
c--aaagactccgtcagcaccgtatgagaaatcaaagtctttgggttccggggggagtat
ggtcgcaaggctgaaacttaaagaaattgacggaagggcaccaccaggagtggagcctgc
ggcttaatttgactcaacacggggaaacttaccaggtccagacatagtaaggattgacag
attgagagctctttcttgattctntgggtggtggtgcatggccgttcttagttggtggag
tgatttgtctggttaattccgttaacgaacgagacccccgcctgctaaatagcgcactga
atgc-ttagcattgagtgatttccgcttcttagagggactgtcggtgactaatcgacgga
agttgggggcaataacaggtctgtgatgcccttagatgtcctgggccgcacgcgcgctac
actgatgcatgcaacgagtttttcactagtgaccttggccggaaggcttgggaaatctgt
gaacgtgcatcgtgatagggattgatttttgcaattctgaatcataaacgaggaattcct
agtaaacgcaagtcatcagcttgcattgattacgtccctgccctttgtacacaccgcccg
tcgcacctaccgatcgaaggtaatgatgagcccttaggattgtcattctcggcacgcaag
tgtt-ggg-agaggcgagaatttgtgcaaatccctacctttagaggaaggtgaagtcg-a
ncaagg--------------------------------
>U14385.1_Dictyocha_speculum_18S_small-subunit_rRNA_gene
cacctggttgatcctgccagtagtcatacgcttgtctcaaagattaagccatgcatgtct
aagtataaacgactttatactgtgaaactgcgtacagctcattaaaccagttatagttta
tttgatattcctctactactcggatacccgtagtaattctagagctaatacgtgcatcaa
atcccaactgcttcggcggacgggacgtcattattagaaagaagccaatgcgacgcaag-
-tcggtactgtggtgagtcatgataattgtacggatcgtatggccttgcgctgacgatgg
atcattcaagtttctgccctatcagctttggatggtagggtattggcctaccatggcttt
aacgggtaacggagaattagggttcgattccggagagggagcctgagagacggctaccac
atccaaggaaggcagcag--gcgcgtaaattacccaatcctgatacagggaggtagtgac
aaaaaataacaatgccgggctt-ttttaagtctggcaattggaatgagaacaatttaaat
cccttatcgaggatcaattggagggcaagtctggtgccagcagccgcggtaattccagct
ccaatagcgtatattaatgttgttgcagttaaaaagctcgtagttggatttctga-tggg
atcgacccg--gtcggctccgaaaggggtcgcact---ggtggtctgtccggtcatcctc
gagg-------ggaggctttctggcattcatttgtt-ggggagtcgacgctcgtcgttta
ctgtgaacaaattagagtgttcaaagcaggctta--g-gccgttgaatacattagcatgg
aat-aataagataggactttggtgg-tt------------------------------ta
ttttgttggtttgcacgccgaagtaatgattaataggagcagttggggatgtccgtattc
gattgtcagaggtgaaattcttggatttattgaagacgaactactgcgaaagcattcatc
aaggatgttttcattaatcaagaacgaaagttaggggatcgaagaagattagataccttc
gtagtcttataccataaactatgccgactagggattggcggtcg--------------ct
tgttcaggctccgtcagcaccttatgagaaatcaaagtctttgggttccggggggagtat
ggtcgcaaggctgaaacttaaagaaattgacggaagggcaccaccaggagtggagcttgc
ggcttaatttgactcaacacgggaaaacttaccaggtccagacatagtaaggattgacag
attgagagctctttcttgattctatgggtggtggtgcatggccgttcttagttggtggag
tgatttgtctggttaattccgttaacgaacgagacccccgcctgctaaatagtgacggga
atgc-tttgcattgctggatc--tacttcttagagggactttcggcgactagccgaagga
agttgggggcaataacaggtctgtgatgcccttagatgtcctgggctgcacgcgcgctac
actgatgcatgcaacgagttt-------agaaccttggctgagaggcctgggtaatctgt
gaacgtgcatcgtgatagggattgatgattgcaactattcatcatgaacgaggaattcct
agtaaacgtgagtcatcagctcacattgattacgtccctgccctttgtacacaccgcccg
tcgcacctaccgattgaatggctcggtgaggcctcaggattctggtctgacaccctaaca
ggag-tct-gatgagaagaatctgtccaaacctcgtcatttagaggaaggtgaagtcgta
acaaggttaccgtaggtgaacctgcagaaggatcaagc
>AY254857.1_Florenciella_parvula_18S_ribosomal_RNA_gene_partial_sequence
---------------------agtcatacgcttgtctcaaagattaagccatgcatgtct
aagtataaacgactctatactgtgaaactgcgtacggctcattaaaccagttatagttta
tttgatattcccctactactcggatacccgtagtaattctagagctaatacgtgcatcaa
cccccaactgagcgatcggacggggggtcattattagatagaagccaatggcgcgcaag-
-cgtgtattgtggtgagtcatgaaaattgtgcggatcgcagggccttgcgccggcgatgg
atcattcaagtttctgccctatcagctttggatggtagggtattggcctaccatggcctt
aacgggtaacggagaattggggttcgattccggagagggagcctgagagacggctaccac
atccaaggaaggcagcag--gcgcgtaaattacccaatcctgacacagggaggtagtgac
aaaaaataacaatgccgggctt-tttcaagtcaggcaattggaatgagaacaatttaaat
cccttatcgaggatcaattggagggcaagtctggtgccagcagccgcggtaattccagct
ccaatagcgtatattaaagttgttgcagttaaaaagctcgtagttggatttctgg-tggg
gctg-tcgg--cctggctccgaaaggggtcgtggt---tagtacacgcctggccatcctc
gggg-------gaagctttgctggcattaagttgtc-ggcggagtgacgctcgtcgttta
ctgtgaacaaattagagtgttcaaagcaggctta--g-gccgttgaatacattagcatgg
aat-aatgagataggactttggtgg-tc------------------------------ta
ttttgttggtttgcacgccgaagtaatgattaataggggcggttgggggtattcgtattc
aattgtcagaggtgaaattcttggatttatggaagacgaactactgcgaaagcatttacc
aaggatgttttcattaatcaagaacgaaagttaggggatcgaagaagattagataccttc
gtagtctta-accataaactatgccgactagggattggcggtcg--------------ct
tgttcaggctccgtcagcaccttatgagaaatcaaagtctttgggttccggggggggtat
ggtcgcaaggctgaaacttaaagaaattgacggaagggcaccaccaggagtggagcctgc
ggcttaatttgactcaacacggggaaacttaccaggtccagacatagtaaggattgacag
attgagagctctttcttgattctatgggtggtggtgcatggccgttcttagttggtggag
tgacttgtctggttaattccgttaacgaacgagacccccgcctgctaaatagtgacggga
atgc-ttcgcattgccgggc---cgcttcttagagggacttttggtgactaaccaaagga
agttgggggcaataacaggtctgtgatgcccttagatgtcctggactgcacgcgcgctac
actgacacatgcaacgagtct-------acaaccttggctggaaggcctgggtaatctgt
gaacgtgtgtcgtgatagggatagattattgcaattattaatcttgaacgaggaattcct
agtaaacgcaaatcatcagcttgcattgattacgtccctgccctttgtacacaccgcccg
tcgcacctaccgattgaatggttcggtgaggtctcaggatcgtggcttagcaccttcatt
ggag-ctc-tgccgtgagaatttgcccaaacctcatcatttagaggaaggtgaagtcgta
acaaggttaccgtag-----------------------
>ASV_285_Dictyochophyceae_Both
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------------agct
ccaatagcgtatattaatgttgttgcagttaaaaagctcgtagttggatttctgg-tggg
agca-ctcg--gtcggctccgcaaggggttgcact---tgt-gtgtctccggcccttttc
gagg-------gaagtatgtctggcattaagttgtc-gggcatgtgacgctcgtcgttta
ctgtgaacaaattagagtgttcaaagcaggctta--g-gccgttgaatacattagcatgg
aat-aatgagataagactctggtgg-tc------------------------------ta
ttttgttggtttgcacaccggtgtaatggttaataggggcagttgggggtattcgtattc
agttgtcagaggtgaaattcttggatttacggaagacgaactactgcgaaagcatttacc
aaggatgttttca-----------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------
>ASV_2195_Dictyochophyceae_Both
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------------agct
ccaatagcgtatattaatgttgttgcagttaaaaagctcgtagttggatttcaga-ttgg
agca-cgcg--gtcggttccgcaagggattgcact----agtgtgtctccggtccttttc
gagg-------ggagcgtgtctggcattgagttgtc-gggcatgtgacgctcgtcgttta
ctgtgaacaaattagagtgttcaaagcaggctta--g-gccgttgaatacattagcatgg
aat-aatgagataagactctggtgg-tc------------------------------ta
ttttgttggtttgcacaccggtgtaatggttaataggggcagttgggggtattcgtattc
agttgtcagaggtgaaattcttggatttacggaagacgaactactgcgaaagcatttacc
aaggatgttttca-----------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------
>ASV_2636_Dictyochophyceae_Both
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------------agct
ccaatagcgtatattaatgttgttgcagttaaaaagctcgtagttggatttctga-tggg
agca-cgcg--gtcggttccgcaagggattgcact----agtgtgtctccggtcattctc
gagg-------ggagcgtgtctggcattaagttgtc-gggcatgtgacgctcgtcgttta
ctgtgaacaaattagagtgttcaaagcaggctta--g-gccgttgaatacattagcatgg
aat-aatgagataagactctggtgg-tc------------------------------ta
ttttgttggtttgcacaccggtgtaatggttaataggggcagttgggggtattcgtattc
agttgtcagaggtgaaattcttggatttacggaagacgaactactgcgaaagcatttacc
aaggatgttttca-----------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------
>ASV_2674_Dictyochophyceae_DNA
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------------agct
ccaatagcgtatattaaagttgttgcagttaaaaagctcgtagttggatttctgg-tggg
agcg-cacg--gtcttccccgaaaggggttgcact---ggtcgcgtctccggccatcctc
gggt-------tgaatccgtctggcattaggttgtc-gggcgggggagactcgtcgttta
ctgtgaacaaattagagtgttcaaagcaggctta--g-gccgttgaatacattagcatgg
aat-aatgagataggactttggtggttt------------------------------ta
ttttgttggtttgcacgccgaagtaatgattaataggagcagttgggggtattcgtattc
aattgtcagaggtgaaattcttggatttatggaagacgaactactgcgaaagcatttacc
aaggatgttttca-----------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------
>ASV_2687_Dictyochophyceae_Both
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------------agct
ccaatagcgtatattaaagttgttgcagttaaaaagctcgtagttggatttctgg-tggg
agcg-cccg--gtcgtccccgaaaggggttgcact---ggtggcgtctccggccatcctc
ggga-------ggagctcgtctggcattgagttgtc-gggcgggtgatgctcgtcgttta
ctgtgaacaaattagagtgttcaaagcaggctta--g-gccgttgaatacattagcatgg
aat-aatgagataggactttggtgg-tc------------------------------ta
ttttgttggtttgcacgccgaagtaatgattaataggagcggttgggggtattcgtattc
aattgtcagaggtgaaattcttggatttacggaagacgaactactgcgaaagcatttacc
aaggatgttttca-----------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------
>ASV_2740_Dictyochophyceae_Both
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------------agct
ccaatagcgtatattaatgttgttgcagttaaaaagctcgtagttggatttctga-tggg
agca-cgcg--gtcggttccgcaagggattgcact---tgt-gtgtctccggtccttttc
gagg-------ggagcgtgtctggcattcagttgtc-gggcatgtgacgctcgtcgttta
ctgtgaacaaattagagtgttcaaagcaggctta--g-gccgttgaatacattagcatgg
aat-aatgagataagactctggtgg-tc------------------------------ta
ttttgttggtttgcacaccggtgtaatggttaataggggcagttgggggtattcgtattc
agttgtcagaggtgaaattcttggatttacggaagacgaactactgcgaaagcatttacc
aaggatgttttca-----------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------
>ASV_3763m_Dictyochophyceae_DNA
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------------agct
ccaatagcgtatattaatgttgttgcagttaaaaagctcgtagttggatttctgg-tagg
agcgcccggtcatcggctccgcaaggagtttgact---ggtggcgcctccggccatcctc
gggg-------ggagttcgtctggcattgagttgtc-gggcggatgacgcccgtcgttta
ctgtgaacaaattagagtgttcaaagcaggctta--t-gccgttgaatacattagcatgg
aat-aatgagataggactttggtgg-tc------------------------------ta
ttttgttggtttgcacgccgaagtaatgattaataggagcggttgggggtattcgtattc
aattgtcagaggtgaaattcttggatttatggaagacgaactactgcgaaagcatttacc
aaggatgttttca-----------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------
>ASV_3859_Dictyochophyceae_Both
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------------agct
ccaatagcgtatattaatgttgttgcagttaaaaagctcgtagttggatttctga-tggg
agca-cgcg--gtcggttccgcaagggattgcact----agcgtgtctccggtccttttc
gagg-------ggagcgtgtctggcattaagttgtc-gggcatgtgacgctcgtcgttta
ctgtgaacaaattagagtgttcaaagcaggctta--g-gccgttgaatacattagcatgg
aat-aatgagataagactctggtgg-tc------------------------------ta
ttttgttggtttgcacaccggtgtaatggttaataggggcagttgggggtattcgtattc
agttgtcagaggtgaaattcttggatttacggaagacgaactactgcgaaagcatttacc
aaggatgttttca-----------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------
>ASV_3895_Dictyochophyceae_Both
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------------agct
ccaatagcgtatattaatgttgttgcagttaaaaagctcgtagttggatttctga-tggg
agca-ttcg--gtcggttccgcaagggattgcact---tgt-atgtctccggtcatcctc
gagg-------gaagtgtgtctggcattaagttgtc-gggcatatgacgctcgtcgttta
ctgtgaacaaattagagtgttcaaagcaggctta--g-gccgttgaatacattagcatgg
aat-aatgagataagactctggtgg-tc------------------------------ta
ttttgttggtttgcacaccggtgtaatggttaataggggcagttgggggtattcgtattc
agttgtcagaggtgaaattcttggatttacggaagacgaactactgcgaaagcatttacc
aaggatgttttca-----------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------
>ASV_4449_Dictyochophyceae_Both
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------------agct
ccaatagcgtatattaaagttgttgcagttaaaaagctcgtagttggatttctgg-tggg
agcg-cccg--gtcgtccccgagaggggttgtact---ggtggcgtctccggccatcctc
ggga-------ggagttcgtctggcattgagttgtc-gggcggatgatgctcgtcgttta
ctgtgaacaaattagagtgttcaaagcaggctta--g-gccgttgaatacattagcatgg
aat-aatgagataggactttggtgg-tc------------------------------ta
ttttgttggtttgcacgccgaagtaatgattaataggagcggttgggggtattcgtattc
aattgtcagaggtgaaattcttggatttacggaagacgaactactgcgaaagcatttacc
aaggatgttttca-----------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------
>ASV_4748_Dictyochophyceae_Both
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------------agct
ccaatagcgtatattaatgttgttgcagttaaaaagctcgtagttggatttctga-tggg
agcg-cgcg--gtcggttccgcaagggattgcact---agtgtgtctccggtcatttctc
gagg-------ggagcgtgtctggcattaagttgtc-gggcatgtgacgctcgtcgttta
ctgtgaacaaattagagtgttcaaagcaggctta--g-gccgttgaatacattagcatgg
aat-aatgagataagactctggtgg-tc------------------------------ta
ttttgttggtttgcacaccggtgtaatggttaataggggcagttgggggtattcgtattc
agttgtcagaggtgaaattcttggatttacggaagacgaactactgcgaaagcatttacc
aaggatgttttca-----------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------
>ASV_5454_Dictyochophyceae_Both
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------------agct
ccaatagcgtatattaatgttgttgcagttaaaaagctcgtagttggatttctgg-tggg
agcg-cccg--gtcggctgcgaaagcggttgcact---ggtggcgtctccggccatcctc
gggg-------cgagcgcatctggcattcagttgtc-gggcgcgtgaactccgtcgttta
ctgtgaacaaattagagtgttcaaagcaggctta--c-gccgttgaatacattagcatgg
aat-aatgagataggacttgggtgg-tc------------------------------ta
ttttgttggtttgcacgcctaagtaatgattaataggggcggttgggggtattcgtattc
aattgtcagaggtgaaattcttggatttatggaagacgaactactgcgaaagcatttacc
aaggatgttttca-----------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------
>ASV_7821_Dictyochophyceae_Both
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------------agct
ccaatagcgtatattaatgttgttgcagttaaaaagctcgtagttggatttctga-tggg
agca-ctcg--gtcggttccgcaagggattgcact---agtgtgtctccggtcatttctc
gagg-------ggagcgtgtctggcattaagttgtc-gggcatgtgacgctcgtcgttta
ctgtgaacaaattagagtgttcaaagcaggctta--g-gccgttgaatacattagcatgg
aat-aatgagataagactctggtgg-tc------------------------------ta
ttttgttggtttgcacaccggtgtaatggttaataggggcagttgggggtattcgtattc
agttgtcagaggtgaaattcttggatttacggaagacgaactactgcgaaagcatttacc
aaggatgttttca-----------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------
>ASV_8705_Dictyochophyceae_Both
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------------agct
ccaatagcgtatattaatgttgttgcagttaaaaagctcgtagttggatttctgg-tggg
agcg-cccg--gtcggctgcgaaagcggttgcact---ggtggcgtctccggccatcctc
gggg-------cgaacatgtctggcattcagttgtc-gggcgtgtgaaccccgtcgttta
ctgtgaacaaattagagtgttcaaagcaggctta--c-gccgttgaatacattagcatgg
aat-aatgagataggacttgggtgg-tc------------------------------ta
ttttgttggtttgcacgcctaagtaatgattaataggggcggttgggggtattcgtattc
aattgtcagaggtgaaattcttggatttatggaagacgaactactgcgaaagcatttacc
aaggatgttttca-----------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------
>ASV_8772_Dictyochophyceae_RNA
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------------agct
ccaatagcgtatattaatgttgttgcagttaaaaagctcgtagttggatttctga-tggg
agca-ttcg--gtcggttccgcaagggattgcact---tgt-atgtctccggtcatcctc
gagg-------gaagtgtgtctggcattgagttgtc-gggcatatgacgctcgtcgttta
ctgtgaacaaattagagtgttcaaagcaggctta--g-gccgttgaatacattagcatgg
aat-aatgagataagactctggtgg-tc------------------------------ta
ttttgttggtttgcacaccggtgtaatggttaataggggcagttgggggtattcgtattc
agttgtcagaggtgaaattcttggatttacggaagacgaactactgcgaaagcatttacc
aaggatgttttca-----------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------
>ASV_10253_Dictyochophyceae_DNA
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------------agct
ccaatagcgtatattaaagttgttgcagttaaaaagctcgtagttggatttctgg-tggg
agcg-cccg--gtcttccccgcaaggggtcgttact--ggtggcgtctccggccatcctc
gggt-------tcgggccgtctggcattaagttgtcgggcggttttcggcccgtcgttta
ctgtgaacaaattagagtgttcaaagcaggctta--g-gccgttgaatacattagcatgg
aat-aatgagataggactttggtgg-tc------------------------------ta
ttttgttggtttgcacgccgaagtaatgattaataggagcagttgggggtattcgtattc
aattgtcagaggtgaaattcttggatttatggaagacgaactactgcgaaagcatttacc
aaggatgttttca-----------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------
>ASV_13010m_Dictyochophyceae_DNA
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------------agct
ccaatagcgtatattaatgttgttgcagttaaaaagctcgtagttggatttctgg-tggg
agca-ctcg--gtcggctgcgaaagcggttgcact---tgcagtgcctctcgccatcttc
tcgc-------ctagcggtgctggcattaaattgtt-gg-gccgtgaagcgggtcgttta
ctgtgaacaaattagagtgttcaaaacaggctta--c-gccgttgaatacattagcatgg
aat-aatgagataggactttggtgg-tc------------------------------ta
ttttgttggtttgcacgccagagtaatgattaatagggacggttgggggtattcgtattc
aattgtcagaggtgaaattcttggatttatggaagacgaactactgcgaaagcatttacc
aaggatgttttca-----------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------
>ASV_13278_Dictyochophyceae_DNA
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------------agct
ccaatagcgtatattaatgttgttgcagttaaaaagctcgtagttggatttctga-tggg
agca-cgcg--gtcggttccgcaagggattgcact---tgt-gtgtctccggtccttttc
gagg-------ggagcgtgtctggcattcagttgtc-gggcatgggacgctcgtcgttta
ctgtgaacaaattagagtgttcaaagcaggctta--g-gccgttgaatacattagcatgg
aat-aatgagataagactctggtgg-tc------------------------------ta
ttttgttggtttgcacaccggtgtaatggttaataggggcagttgggggtattcgtattc
agttgtcagaggtgaaattcttggatttacggaagacgaactactgcgaaagcatttacc
aaggatgttttca-----------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------
>ASV_17852_Dictyochophyceae_RNA
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------------agct
ccaatagcgtatattaatgttgttgcagttaaaaagctcgtagttggatttctga-tggg
agca-ttcg--gtcggttccgcaagggattgcact---tgt-atgtctccggtcatcctc
gagg-------gaagtgtgtctggcattaatttgtc-gggcatatgacgctcgtcgttta
ctgtgaacaaattagagtgttcaaagcaggctta--g-gccgttgaatacattagcatgg
aat-aatgagataagactctggtgg-tc------------------------------ta
ttttgttggtttgcacaccggtgtaatggttaataggggcagttgggggtattcgtattc
agttgtcagaggtgaaattcttggatttacggaagacgaactactgcgaaagcatttacc
aaggatgttttca-----------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------
>ASV_21835_Dictyochophyceae_RNA
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------------agct
ccaatagcgtatattaaagttgttgcagttaaaaagctcgtagttggatttctgg-tggg
agcg-cacg--gtcttccccgaaaggggttgcact---ggtcgcgtctccggccatcctc
gggt-------tgaatccgtctggcattaggttgtc-gggcgggggagactcgtcgttta
ctgtgaacaaattagagtgttcaaagcaggctta--g-gccgttgaatacattagcatgg
aat-aatgagataggactttggtgg-tc------------------------------ta
ttttgttggtttgcacgccgaagtaatgattaataggagcagttgggggtattcgtattc
aattgtcagaggtgaaattcttggatttatagaagacgaactactgcgaaagcatttacc
aaggatgttttca-----------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------
>ASV_22804_Dictyochophyceae_DNA
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------------agct
ccaatagcgtatattaatgttgttgcagttaaaaagctcgtagttggatttctgg-ttgg
gcttgcccg--gtcggctgcgaaagtggttgtact---cggcgcgatcctggctttcctc
ggga-------caaacttgcctggcattcagttgtc-ggacttgtgaatcccgtcgttta
ctgtgaacaaattagagtgttcaaagcaggctta--c-gccgttgaatacattagcatgg
aat-aataagataggactttggtgg-tc------------------------------ta
ttttgttggtttgcacgccgaagtaatgattaatagggacagttgggggtattcgtattc
aattgtcagaggtgaaattcttggatttatggaagacgaactactgcgaaagcatttacc
aaggatgttttca-----------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------
>U14389.1_Pelagomonas_calceolata_18S_small-subunit_rRNA_gene
cacctggttgatcctgccagtagtcatacgctcgtctcaaagattaagccatgcatgtct
aagtataagcgatcttgtactgtgaaactgcgaatggctcattatatcagttatagttta
tttgatagtcccttactacatggatacccgtagtaattctagagctaatacatgcatcga
ctcccaactgcttcggcgggcgggacgtatttattagattgaaaccaatgcgggggagac
cccggtattgtggtgagtcatgataactttgcgaatcgcatggcttcgtgccggcgatgg
atcattcaagtttctgccctatcagctttggatggtagggtattggcctaccatggcatt
aacgggtaacggagaattggggttcgattccggagagggagcctgagagacggctaccac
atccaaggaaggcagcag--gcgcgtaaattacccaatcctgacacagggaggtagtgac
aagaaataacaatgccgggctc-ttacgagtctggcaattggaatgagaacaatttaaat
cccttatcgaggatccattggagggcaagtctggtgccagcagccgcggtaattccagct
ccaatagcgtatattaatgttgttgcagttaaaaagctcgtagttggattcctgacctgg
ggta-gccg--gtccgccttgcaaaaggtgcgcac----tgagcggcctcggtcatcctt
gaga-------agagcggtcctggcattcagttgtc-ggggtcgggattctcgacgttta
ctgtgaaaaaatcagagtgttcaacgcaggctta--c-gc-cttgaatacattagcatgg
aat-aatgagataggaccttggcgg-tc------------------------------ta
ttttgttggtttgcacgccgaggtaatgattaaaagggacggttggggttcttcgtattc
aattgtcagaggtgaaattcttggatttatggaagacgaactgctgcgaaagcgtcgaac
aaggacgttctcattaatcaagaacgaaagttaggggatcgaagatgattagataccatc
gtagtctta-accataaactatgccgattcaggattggcggtcg-------------ttt
gttctcgactccgtcagcactgtatgagaaatcaaaatctttgggttccggggggagtat
ggtcgcaaggctgaaacttaaagaaattgacggaagggcaccaccaggagtggagcctgc
ggcttaatttgactcaacacggggaaacttaccaggtccagacatagtaaggattgacag
attgagagctctttcttgattctatgggtggtggtgcatggccgttcttagttggtggag
tgatttgtctggttaattccgttaacgaacgagacccccgcctgctaaataggtgcggga
atgcgcttgcattgctg-----caacttcttagagggactttcggtgactaaccgaagga
agctgggggcaataacaggtctgtgatgcccttagatgtcctgggccgcacgcgcgctac
actggcacacgcaacgagtct-------atcaccttggtcggcaggcctgggtaatctgt
gaacgtgtgccgtgattgggattgattgttgcaattttcaatcatgaacgaggaattcct
agtaaacgcgagtcatcagctcgcattgattacgtccctgccctttgtacacaccgcccg
tcgcacctaccgattgaatggttcggtgaaatctccggattggagcacgcaagcttcacg
gcga-acg-tgctttgagaagttgattaaacctcactatttagaggaaggtgaagtcgta
acaaggtttccgtaggtgaacctgcagaaggatcaagc
>ASV_5982_Dictyochophyceae_DNA
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------------agct
ccaatagcgtatattaatgttgttgcagttaaaaagctcgtagttggatttctgg-tggg
agca-cgcg--gtcggctgcgcaagcggttgcact---tgctgtgcctctcgcccttctc
tcgc-------ctagcggcactggcattaacttgtt-gg-gtcgtgaagcgggtcgttta
ctgtgaacaaattagagtgttcaaaacaggctta--c-gccgttgaatacattagcatgg
aat-aataagataggacttgggtgg-tc------------------------------ta
ttttgttggtttgcacgcctaagtaatgattaatagggacggttgggggtattcgtattc
aattgtcagaggtgaaattcttggatttatggaagacgaactactgcgaaagcatttacc
aaggatgttttca-----------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------
>ASV_9475_Dictyochophyceae_Both
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------------agct
ccaatagcgtatattaaagttgttgcagttaaaaagctcgtagttggatttctggtctgg
aggg-cgcg--gtcggcccctcacggggtgcacttgt-tgccttttaccgggccactttc
gggg-------ggagccttcctggcattcagttgtc-gggggggcaacgctcgtcgttta
ctgtgaacaaattagagtgttcaaagcaggcttg--atgccgttgaatacattagcatgg
aat-aatgagataggactttggttg-tc------------------------------ta
ttttgttggtttgcacgccgaagtaatgattaataggagcagttgggggtattcgtattc
agttgtcagaggtgaaattcttggatttacggaagacggactactgcgaaagcatttacc
aaggatgttttca-----------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------
>ASV_22568_Dictyochophyceae_DNA
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------------agct
ccaatagcgtatattaatgttgttgcagttaaaaagctcgtagttggatttttgg-ttgg
gcttgctcg--gtcggctgcgaaagtggttgtact---cggtgcgatcctggcttttttc
ggga-------ctatcatgtctacccttaactgggc-gggcctgtgaatcctgtcgttta
ctgtgaacaaattagagtgttcaaagcaggctta--c-gccgttgaatacattagcatgg
aat-aataagataggactttggtgg-tc------------------------------ta
ttttgttggtttgcacgccgaagtaatgattaatagggacagttgggggtattcgtattc
aattgtcagaggtgaaattcttggatttatggaagacgaactactgcgaaagcatttacc
aaggatgttttca-----------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------
>M87329.1_Rhizosolenia_setigera_16S-like_ribosomal_RNA_complete
aacctggttgatcctgccagtagtcatacgctcgtctcaaagattaagccatgcatgtgt
aagtataaata---ttttatagtaaaactgcgaatggctcattaaatcagtattaattta
catgataat-ccttactacttggataaccgtagtaattctagagctaatacatgcttaaa
tgccgactg----cttgcagaaggcagcatttattagatagaagccatccctcttcgga-
---ggtattttggtgaatcataataactttgcggatcgcatggctctacgccggcgacag
atcattcaagtttctgccctattagatttggatggctgtgtattggacagccatgtcttt
gatgggtaacggagaattagggtccgattccggagagggagcctgagagacggctaccac
atccaaggaaggcagcag--gcgcgtaaattacccaatcctgacacagggaggtagtgac
aataaataacaatgccgggtct-actaagatctggcaattggaatgagaacaatttaaat
cccttatcgaggatcaattggagggcaagtctggtgccagcagccgcggtaattccagct
ccaatagcgtatattaaagttgttgcagttaaaaagctcgtagttgaatttctgg-tggg
agcg-atcg--gtccatccttcactggttggaacc----tgattgtctcccgccatccat
ggag-------agaacttatctggcattaagttgtc-gggttggcaatcttcatctttta
ctgtgaaaaaattagagtgttcaaagcaggctta--t-gccgttgaatatattagcatgg
aat-aataagataggactatggt---------------------------------acta
ttttgttggtttgtgcaccatggtaatgattaatagggacagttgggggtattcgtattc
cattgtcagaggtgaaattcttggatttatggaagacgaactactgcgaaagcatttacc
aaggatgttttcattaatcaagaacgaaagttaagggatcgaagatgattagataccatc
gtagtctta-accataaactatgccaactagagatcggcagttgttaa------------
---tatgacactgtcggcatcttatgagaaatcaaagtctttgggttccggggggagtat
ggtcgcaaggctgaaacttaaagaaattgacggaagggcaccaccaggagtggag-ctgc
ggcttaatttgactcaacacgggaaaacttaccaggtccagacatagtgaggattgacag
attgagagctctttcttgattctatgggtggtggtgcatggccgttcttagttggtggat
tgatttgtctgcttaattgcgttaacgaacgagacccccgcctgctaaataatcacgtga
atga-attatcattgatgat---ggtttcttagagggacttttggtgactaaccaaagga
agttgggggcaataacaggtctgtgatgcccttagatgttctgggccgcacgcgcgctac
actgatgcattcaacgagctt-------ataaccttggccgagaggctgggcaatctttt
aaacgtgcatcgtgatagggatagattattgcaattattaatcttgaacgaggaattcct
agtaaacgcagatcatcaatctgcattgattacgtccctgccctttgtacacaccgcccg
tcgcacctaccgattgaatggtccggtgaggcctcgggattgtggtctggttgctttatt
ggaa-cct-gactgtgagaacctgtccaaaccttatcatttagaggaaggtgaagtcgta
acaaggtttccgtaggtgaacctgcagaaggatcaagc
>ASV_7653_Dictyochophyceae_RNA
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------------agct
ccaatagcgtatattaaagttgttgcagttaaaaagctcgtagtcggacttctgg-tggg
agcc-tgcg--gttggctccgaaaggggttgttac---cagcgggtctccggccatcctt
gagg-------ggagcgcgtctggcctttactggtc-gggcgtgtgacgctcatcgttta
ctgtgaacaaatccaatggcttcaacaaatacgt--a-agtattgaagacattagcatgg
aat-aataagataggactttggtgg-tc------------------------------ta
ttttgttggtttgcactccgaagtaatgattaatagaggcggttggggttattcgtattt
agttgtcagaggtgaaattcttggatttacgaaagacgaactactgcgaaagcatttaac
aaagatgttttca-----------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------
>ASV_13685_Dictyochophyceae_RNA
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------------agct
ccaatagcgtatattaaagttgttgcagttaaaaagctcgtagttggatttctgg-tggg
agcc-tgcg--gtcggctccgaaaggggttgcaac---cagcgggtctccggccatcctt
tggg-------ggagcgcgtctggccttcactggtc-gggcgtgtgacgccaatcgttta
ctgtgaacaaattagagtgttcaaagcaaagcgtacg-ctttttgaatacattagcatgg
aat-aataagataggactccgatgg-tc------------------------------ta
ttttgttggtttgcacattggagtaatgattaatagggacggttgggggtattcgtattt
agttgtcagaggtgaaattcttggatttacgaaagacgaactactgcgaaagcatttacc
atggatgttttca-----------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------
>ASV_17867_Dictyochophyceae_RNA
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------------agct
ccaatagcgtatattaaagttgttgcagttaaaaagctcgtagttggatttctgg-tggg
agcc-tgcg--gtcggctccgaaaggggttgcaac---cagctggtctccggccatcctt
tggg-------ggagcgcgtctggccttcactggtc-gggcgtgtgacgccaatcgttta
ctgtgaacaaattagagtgttcaaagcaaagcgtacg-ctttttgaatacattagcatgg
aat-aataagataggactccgatgg-tc------------------------------ta
ttttgttggtttgcacattggagtaatgattaatagggacggttgggggtattcgtattt
agttgtcagaggtgaaattcttggatttacgaaagacgaactactgcgaaagcatttacc
atggatgttttca-----------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------
>AF123285.1_Chromulina_nebulosa_small_subunit_ribosomal_RNA_gene_partial_sequence
-tcctggttgatcctgccagtag-catacgcttgtctcaaagattaagccatgcatgtct
aagtataagcat--ttatacagtgaaactgcgaatggctcattatatcagttatagttta
tttgatggt-ctttgctacttggataaccgtagtaattctagagctaatacatgcataaa
acctcaact------tacgacgaggtgtatttattagatggaaaccaatgcggggaaac-
-ccggta-aatggtgattcataataactttcgga-----------tcgagtaatcgatgc
atcattcaagtttctgccctatcagctttggatggtagggtattggcctaccatggcttt
aacgggtaacggagaattagggttcgattccggagagggagcctgagaaacggctaccac
atctaaggaaggcagcag--gcgcgtaaattacccaatcctgacacagggaggtagtgac
aataaataacaatgctgggc---tttctagtttggcaattggaatgagaacgatttaaat
cccctatcgaggatcaattggagggcaagtctggtgccagcagccgcggtaattccagct
ccaatagcgtatactaaagttgttgcagttaaaaagctcgtagttgaacttctgg-cgaa
tatc-ttat--gtccgatcttcacggattgcgtac----gtgagactatttaccatcttt
gcaa-------gaggtgtatgtgttcttaattgaat-ggatataaaccttgcatcattta
ctgtgagcaaactagagtgttcaaagcaggctta--a-gccattgaatacattagcatgg
aat-aataatataagaccttgtt----------------------------------tta
ttttgttggtttatattccaaggtaatgataaatagggacagttgggggtattcgtattc
aatagtcagaggtgaaattcttggatttatggaagacgaactactgcgaaagcatttacc
aaggatgttttcattaatcaagaacgaaagtaaggggatcgaagatgattagataccatc
gtagtctta-accataaactatgccgactagggatgggtagacgttg-------------
--ttttgactctatccgcaccttatgagaaatcaaagtctttgggttccggggggagtat
ggtcgcaaggctgaaacttaaagaaattgacggaagggcaccaccaggagtggagcctgc
ggcttaatttgactcaacacggggaaacttaccaggtccagacatagtgaggattgacag
attgatagctctttcttgattctatgggtggtggtgcatggccgttcttagttggtggag
tgatttgtctggttaattccgttaacgaacgagacccccgcctgctaaatagattaacga
atac-tttgtatttgtcgaat----cttcttagagggacttttggtgactaaccaaagga
agttgggggcaataacaggtctgtgatgcccttagatgttctgggccgcacgcgcgctac
actgacagactcagtgagttt-----------cctagtccgaaaggcctgggtaatc-tt
taatgtctgtcgtgatagggatagattattgcaattattaatcttgaacgaggaattcct
agtaaatgcgagtcatcagctcgcgttgattacgtccctgccctttgtacacaccgcccg
tcgcacctaccgattgaatgattcggtgaaaatctcggactgtagtattgaagccctcgg
gcta-cta-tatcataggaagttatttaaacctcatcatttagaggaaggtgaagtcgta
acaaggtttccgtaggtgaacctgcagaagaatcaa--
